name: Documentation checks

on:
  - push
  - pull_request

jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true
          woke-args: "*.md **/*.md -c https://github.com/canonical-web-and-design/Inclusive-naming/raw/main/config.yml"

  spellcheck:
    name: Spelling check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Aspell
        run: |
          sudo apt-get install aspell aspell-en

      - name: Build docs and run spelling checker
        run: |
          make doc-spellcheck

  linkcheck:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run linkchecker
        run: |
          make doc-linkcheck

  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install mdl
        run: |
          sudo snap install mdl

      - name: Run mdl
        run: |
          make doc-lint
